### ISSUE TITLE
issue with responsive nav header

### ISSUE THREAD

**Issue by thob** [GabrielDelepine/smooth-scroll#10]
it seems that the script makes the anchor based css navigation unusable when in mobile mode. It doesn't show the menu items. Is there an option to exclude it from the scroll feature?

Here's the [page](https://socialware.at/bright-learning-architecture)

Thanks

**Comment by GabrielDelepine** [comment]
Hi @thob,

Sorry for the delay. 
I don't see the plugin in the page you mention. Are you still experiencing this issue ?

**Comment by thob** [comment]
I think my problem ist related to the `a` tag if it's also used for css-based menus. [See](https://socialware.at/messenger-content-marketing).
