### ISSUE TITLE
Please add to NPM registry

### ISSUE THREAD

**Issue by XmlmXmlmX** [GabrielDelepine/smooth-scroll#12]
Please add to NPM registry

**Comment by GabrielDelepine** [comment]
unfortunatly, `smooth-scroll` is already reserved by someone else in the npm registry

**Comment by GabrielDelepine** [comment]
I publish it under the scoped name `@gabriel-delepine/smooth-scroll`

Thanks for opening this issue !

About scoped name : https://docs.npmjs.com/getting-started/scoped-packages
