### ISSUE TITLE
Can you please tag 1.4.0 version? 

### ISSUE THREAD

**Issue by brodock** [GabrielDelepine/smooth-scroll#14]
I'm trying to use https://rails-assets.org which will use bower's repository + tag system. All you need to do is tag your current master with the same version in your bower.json

**Comment by GabrielDelepine** [comment]
Hi @brodock 

I did it. Can you tell me if it's ok for you? I'm not using bower, sorry about the inconvenience.

**Comment by brodock** [comment]
All good, thanks :)
